version: "3"
services:
  web:
    build: .
    ports:
      - "4000:5000"
  mysql:
    image: mysql
    command: --default-authentification-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
      MYSQL_HOST: mysql_server
      NODEJS_LOCAL_PORT: 3000
    ports :
      - 9002:9002
